# banking_analytics:
#   outputs:
#     spark:
#       auth: NOSASL
#       method: thrift
#       connect_timeout: 30
#       host: spark-thrift
#       port: 10000
#       schema: analytics
#       threads: 2
#       timeout_seconds: 300
#       type: spark
#       user: spark
#   target: spark

banking_analytics:
  outputs:
    spark:
      auth: NOSASL
      method: thrift
      connect_timeout: 30
      host: spark-thrift
      port: 10000
      schema: analytics
      threads: 2
      timeout_seconds: 300
      type: spark
      user: spark
      spark_conf:
        spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
        spark.hadoop.fs.s3a.connection.ssl.enabled: "false"
        spark.hadoop.fs.s3a.path.style.access: "true"

        # 1. Disable JVM caching so Spark actually applies these custom timeouts
        spark.hadoop.fs.s3a.impl.disable.cache: "true"

        # 2. Optimize stream reading for large sequential CSV inferences
        spark.hadoop.fs.s3a.experimental.input.fadvise: "sequential"

        # 3. Connection stability parameters
        spark.hadoop.fs.s3a.connection.timeout: "600000"
        spark.hadoop.fs.s3a.connection.establish.timeout: "60000"
        spark.hadoop.fs.s3a.attempts.maximum: "10"
  target: spark
