banking_analytics:
  outputs:
    spark:
      auth: NOSASL
      method: thrift
      connect_timeout: 30
      driver: org.apache.hive.jdbc.HiveDriver
      host: spark-thriftserver
      port: 10000
      schema: analytics
      threads: 2
      timeout_seconds: 300
      type: spark
      user: spark
  target: spark
